name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps (with cache)
        run: npm install

      - name: Check formatting
        run: npm run format:check
    
      - name: Build, lint, test, and typecheck
        run: npm run build && npm run lint && npm install --prefix demo && npm run test

      - name: list files
        run: ls ./demo
