name: Upload Schema Files

on:
  pull_request:
    types:
      - closed
    branches:
      - test-main

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true && github.head_ref == 'test-release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout the repo
        uses: actions/checkout@v4
        
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: list files
        run: ls -R

      - name: Upload to S3
        run: |
          aws s3 cp test.txt s3://five12daysgeneral/ftd-core/test.txt      
