name: Upload Schema Files

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true && github.head_ref == 'release-please--branches--main--components--release-please-action' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Upload to S3
        run: |
          aws s3 cp templateSchemas/ftdConfig.schema.json s3://five12daysgeneral/ftd-core/ftdConfig.schema.json && aws s3 cp templateSchemas/ftdModel.schema.json s3://five12daysgeneral/ftd-core/ftdModel.schema.json
