name: Upload Schema Files

on:
  pull_request:
    types:
      - closed
    branches:
      - test-main

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"